version: '3'

# Definition of application services (containers)
services:
 # Configuration for database container
 db:
   build: ./database
   restart: always

 # (optional) Container for managing the database via the web interface
 adminer:
   image: adminer
   restart: always
   ports:
     - 8080:8080

 # Configuration for frontend container
 frontend:
   build: ./pyramid_app/frontend
   ports:
   - 3000:3000
   command: npm start
   depends_on:
     - backend

 # Configuration for backend container
 backend:
   build: ./pyramid_app
   ports:
     - 6543:6543
   command: pserve --reload development.ini
   depends_on:
     - db
